// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SysPitstops.Api.Data;
using SysPitstops.Api.Domain;

#nullable disable

namespace SysPitstops.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "item_type", new[] { "PART", "SERVICE" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "movement_type", new[] { "ADJUSTMENT", "IN", "OUT" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "quote_status", new[] { "APPROVED", "EXPIRED", "REJECTED", "SENT" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "service_order_status", new[] { "AWAITING_APPROVAL", "CANCELED", "CONFIRMED", "DELIVERED", "IN_PROGRESS", "IN_YARD", "READY", "REQUESTED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_role", new[] { "ADMIN", "ATTENDANT", "MECHANIC" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence<int>("service_order_number_seq");

            modelBuilder.Entity("SysPitstops.Api.Domain.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Document")
                        .HasColumnType("text")
                        .HasColumnName("document");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("WorkshopId")
                        .HasColumnType("integer")
                        .HasColumnName("workshop_id");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("WorkshopId", "Phone")
                        .HasDatabaseName("ix_customers_phone");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("SysPitstops.Api.Domain.Part", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("CostPrice")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("cost_price");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<decimal>("MinQuantity")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasDefaultValue(0m)
                        .HasColumnName("min_quantity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("QuantityOnHand")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasDefaultValue(0m)
                        .HasColumnName("quantity_on_hand");

                    b.Property<decimal>("SalePrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("sale_price");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("UN")
                        .HasColumnName("unit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("WorkshopId")
                        .HasColumnType("integer")
                        .HasColumnName("workshop_id");

                    b.HasKey("Id")
                        .HasName("pk_parts");

                    b.HasIndex("WorkshopId")
                        .HasDatabaseName("ix_parts_low_stock")
                        .HasFilter("quantity_on_hand <= min_quantity");

                    b.HasIndex("WorkshopId", "Sku")
                        .IsUnique()
                        .HasDatabaseName("uq_parts_sku");

                    b.ToTable("parts", null, t =>
                        {
                            t.HasCheckConstraint("ck_parts_cost_price", "cost_price >= 0");

                            t.HasCheckConstraint("ck_parts_sale_price", "sale_price >= 0");
                        });
                });

            modelBuilder.Entity("SysPitstops.Api.Domain.Quote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("ItemsSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("items_snapshot");

                    b.Property<string>("PublicToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("public_token");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.Property<DateTimeOffset?>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<DateTimeOffset>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("SentBy")
                        .HasColumnType("uuid")
                        .HasColumnName("sent_by");

                    b.Property<Guid>("ServiceOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_order_id");

                    b.Property<QuoteStatus>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("quote_status")
                        .HasDefaultValue(QuoteStatus.Sent)
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_amount");

                    b.HasKey("Id")
                        .HasName("pk_quotes");

                    b.HasIndex("PublicToken")
                        .IsUnique()
                        .HasDatabaseName("uq_quotes_token");

                    b.HasIndex("SentBy")
                        .HasDatabaseName("ix_quotes_sent_by");

                    b.HasIndex("ServiceOrderId", "SentAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_quotes_order");

                    b.ToTable("quotes", null, t =>
                        {
                            t.HasCheckConstraint("ck_quotes_total", "total_amount >= 0");
                        });
                });

            modelBuilder.Entity("SysPitstops.Api.Domain.ServiceOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ApprovalWaivedNote")
                        .HasColumnType("text")
                        .HasColumnName("approval_waived_note");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("text")
                        .HasColumnName("diagnosis");

                    b.Property<decimal>("DiscountAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("discount_amount");

                    b.Property<Guid?>("MechanicId")
                        .HasColumnType("uuid")
                        .HasColumnName("mechanic_id");

                    b.Property<int?>("Mileage")
                        .HasColumnType("integer")
                        .HasColumnName("mileage");

                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("number")
                        .HasDefaultValueSql("nextval('service_order_number_seq')");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ReportedIssue")
                        .HasColumnType("text")
                        .HasColumnName("reported_issue");

                    b.Property<DateTimeOffset?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<ServiceOrderStatus>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("service_order_status")
                        .HasDefaultValue(ServiceOrderStatus.Requested)
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.Property<int>("WorkshopId")
                        .HasColumnType("integer")
                        .HasColumnName("workshop_id");

                    b.HasKey("Id")
                        .HasName("pk_service_orders");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_service_orders_created_by");

                    b.HasIndex("CustomerId", "OpenedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_so_customer");

                    b.HasIndex("MechanicId", "Status")
                        .HasDatabaseName("ix_so_mechanic");

                    b.HasIndex("VehicleId", "OpenedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_so_vehicle");

                    b.HasIndex("WorkshopId", "Number")
                        .IsUnique()
                        .HasDatabaseName("uq_service_orders_number");

                    b.HasIndex("WorkshopId", "OpenedAt")
                        .HasDatabaseName("ix_so_opened_at");

                    b.HasIndex("WorkshopId", "Status")
                        .HasDatabaseName("ix_so_status");

                    b.ToTable("service_orders", null, t =>
                        {
                            t.HasCheckConstraint("ck_so_discount", "discount_amount >= 0");
                        });
                });

            modelBuilder.Entity("SysPitstops.Api.Domain.ServiceOrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<ItemType>("ItemType")
                        .HasColumnType("item_type")
                        .HasColumnName("item_type");

                    b.Property<Guid?>("PartId")
                        .HasColumnType("uuid")
                        .HasColumnName("part_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("ServiceOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_order_id");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_service_order_items");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_service_order_items_created_by");

                    b.HasIndex("PartId")
                        .HasDatabaseName("ix_service_order_items_part_id");

                    b.HasIndex("ServiceOrderId")
                        .HasDatabaseName("ix_soi_order");

                    b.ToTable("service_order_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_item_part_required", "(item_type = 'PART' AND part_id IS NOT NULL) OR (item_type = 'SERVICE' AND part_id IS NULL)");

                            t.HasCheckConstraint("ck_item_quantity", "quantity > 0");

                            t.HasCheckConstraint("ck_item_unit_price", "unit_price >= 0");
                        });
                });

            modelBuilder.Entity("SysPitstops.Api.Domain.ServiceOrderMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Caption")
                        .HasColumnType("text")
                        .HasColumnName("caption");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<Guid>("ServiceOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_order_id");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_key");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id")
                        .HasName("pk_service_order_media");

                    b.HasIndex("ServiceOrderId")
                        .HasDatabaseName("ix_som_order");

                    b.HasIndex("UploadedBy")
                        .HasDatabaseName("ix_service_order_media_uploaded_by");

                    b.ToTable("service_order_media", (string)null);
                });

            modelBuilder.Entity("SysPitstops.Api.Domain.ServiceOrderStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by");

                    b.Property<ServiceOrderStatus?>("FromStatus")
                        .HasColumnType("service_order_status")
                        .HasColumnName("from_status");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<Guid>("ServiceOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_order_id");

                    b.Property<ServiceOrderStatus>("ToStatus")
                        .HasColumnType("service_order_status")
                        .HasColumnName("to_status");

                    b.HasKey("Id")
                        .HasName("pk_service_order_status_history");

                    b.HasIndex("ChangedBy")
                        .HasDatabaseName("ix_service_order_status_history_changed_by");

                    b.HasIndex("ServiceOrderId", "ChangedAt")
                        .HasDatabaseName("ix_sosh_order");

                    b.ToTable("service_order_status_history", (string)null);
                });

            modelBuilder.Entity("SysPitstops.Api.Domain.StockMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<MovementType>("MovementType")
                        .HasColumnType("movement_type")
                        .HasColumnName("movement_type");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid")
                        .HasColumnName("part_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("quantity");

                    b.Property<Guid?>("ServiceOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_order_id");

                    b.Property<decimal?>("UnitCost")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("unit_cost");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("WorkshopId")
                        .HasColumnType("integer")
                        .HasColumnName("workshop_id");

                    b.HasKey("Id")
                        .HasName("pk_stock_movements");

                    b.HasIndex("ServiceOrderId")
                        .HasDatabaseName("ix_sm_order");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_stock_movements_user_id");

                    b.HasIndex("WorkshopId")
                        .HasDatabaseName("ix_stock_movements_workshop_id");

                    b.HasIndex("PartId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_sm_part");

                    b.ToTable("stock_movements", null, t =>
                        {
                            t.HasCheckConstraint("ck_sm_quantity", "quantity > 0");
                        });
                });

            modelBuilder.Entity("SysPitstops.Api.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<UserRole>("Role")
                        .HasColumnType("user_role")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("WorkshopId")
                        .HasColumnType("integer")
                        .HasColumnName("workshop_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("WorkshopId", "Email")
                        .IsUnique()
                        .HasDatabaseName("uq_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SysPitstops.Api.Domain.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("brand");

                    b.Property<string>("Color")
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<int?>("ModelYear")
                        .HasColumnType("integer")
                        .HasColumnName("model_year");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plate");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Vin")
                        .HasColumnType("text")
                        .HasColumnName("vin");

                    b.Property<int>("WorkshopId")
                        .HasColumnType("integer")
                        .HasColumnName("workshop_id");

                    b.HasKey("Id")
                        .HasName("pk_vehicles");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_vehicles_owner");

                    b.HasIndex("WorkshopId", "Plate")
                        .IsUnique()
                        .HasDatabaseName("uq_vehicles_plate");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("SysPitstops.Api.Domain.Workshop", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Document")
                        .HasColumnType("text")
                        .HasColumnName("document");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("pk_workshops");

                    b.ToTable("workshops", (string)null);
                });

            modelBuilder.Entity("SysPitstops.Api.Domain.Customer", b =>
                {
                    b.HasOne("SysPitstops.Api.Domain.Workshop", "Workshop")
                        .WithMany()
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customers_workshops_workshop_id");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("SysPitstops.Api.Domain.Part", b =>
                {
                    b.HasOne("SysPitstops.Api.Domain.Workshop", "Workshop")
                        .WithMany()
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_parts_workshops_workshop_id");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("SysPitstops.Api.Domain.Quote", b =>
                {
                    b.HasOne("SysPitstops.Api.Domain.User", "SentByUser")
                        .WithMany()
                        .HasForeignKey("SentBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_quotes_users_sent_by");

                    b.HasOne("SysPitstops.Api.Domain.ServiceOrder", "ServiceOrder")
                        .WithMany("Quotes")
                        .HasForeignKey("ServiceOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quotes_service_orders_service_order_id");

                    b.Navigation("SentByUser");

                    b.Navigation("ServiceOrder");
                });

            modelBuilder.Entity("SysPitstops.Api.Domain.ServiceOrder", b =>
                {
                    b.HasOne("SysPitstops.Api.Domain.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_orders_users_created_by");

                    b.HasOne("SysPitstops.Api.Domain.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_orders_customers_customer_id");

                    b.HasOne("SysPitstops.Api.Domain.User", "Mechanic")
                        .WithMany()
                        .HasForeignKey("MechanicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_service_orders_users_mechanic_id");

                    b.HasOne("SysPitstops.Api.Domain.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_orders_vehicles_vehicle_id");

                    b.HasOne("SysPitstops.Api.Domain.Workshop", "Workshop")
                        .WithMany()
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_orders_workshops_workshop_id");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Customer");

                    b.Navigation("Mechanic");

                    b.Navigation("Vehicle");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("SysPitstops.Api.Domain.ServiceOrderItem", b =>
                {
                    b.HasOne("SysPitstops.Api.Domain.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_order_items_users_created_by");

                    b.HasOne("SysPitstops.Api.Domain.Part", "Part")
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_service_order_items_parts_part_id");

                    b.HasOne("SysPitstops.Api.Domain.ServiceOrder", "ServiceOrder")
                        .WithMany("Items")
                        .HasForeignKey("ServiceOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_order_items_service_orders_service_order_id");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Part");

                    b.Navigation("ServiceOrder");
                });

            modelBuilder.Entity("SysPitstops.Api.Domain.ServiceOrderMedia", b =>
                {
                    b.HasOne("SysPitstops.Api.Domain.ServiceOrder", "ServiceOrder")
                        .WithMany("Media")
                        .HasForeignKey("ServiceOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_order_media_service_orders_service_order_id");

                    b.HasOne("SysPitstops.Api.Domain.User", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_order_media_users_uploaded_by");

                    b.Navigation("ServiceOrder");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("SysPitstops.Api.Domain.ServiceOrderStatusHistory", b =>
                {
                    b.HasOne("SysPitstops.Api.Domain.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_order_status_history_users_changed_by");

                    b.HasOne("SysPitstops.Api.Domain.ServiceOrder", "ServiceOrder")
                        .WithMany("StatusHistory")
                        .HasForeignKey("ServiceOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_order_status_history_service_orders_service_order_id");

                    b.Navigation("ChangedByUser");

                    b.Navigation("ServiceOrder");
                });

            modelBuilder.Entity("SysPitstops.Api.Domain.StockMovement", b =>
                {
                    b.HasOne("SysPitstops.Api.Domain.Part", "Part")
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_movements_parts_part_id");

                    b.HasOne("SysPitstops.Api.Domain.ServiceOrder", "ServiceOrder")
                        .WithMany()
                        .HasForeignKey("ServiceOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_stock_movements_service_orders_service_order_id");

                    b.HasOne("SysPitstops.Api.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_movements_users_user_id");

                    b.HasOne("SysPitstops.Api.Domain.Workshop", "Workshop")
                        .WithMany()
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_movements_workshops_workshop_id");

                    b.Navigation("Part");

                    b.Navigation("ServiceOrder");

                    b.Navigation("User");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("SysPitstops.Api.Domain.User", b =>
                {
                    b.HasOne("SysPitstops.Api.Domain.Workshop", "Workshop")
                        .WithMany()
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_workshops_workshop_id");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("SysPitstops.Api.Domain.Vehicle", b =>
                {
                    b.HasOne("SysPitstops.Api.Domain.Customer", "Owner")
                        .WithMany("Vehicles")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vehicles_customers_owner_id");

                    b.HasOne("SysPitstops.Api.Domain.Workshop", "Workshop")
                        .WithMany()
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vehicles_workshops_workshop_id");

                    b.Navigation("Owner");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("SysPitstops.Api.Domain.Customer", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("SysPitstops.Api.Domain.ServiceOrder", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Media");

                    b.Navigation("Quotes");

                    b.Navigation("StatusHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
